// === COCKTAIL DATA ===
const COCKTAILS = [
  {id:"C00001",name:"アロアロ",nameEn:"Alo Alo",desc:"ハワイ語でハイビスカスを表すには「たくさんの人に愛される」という意味が……沖縄とハワイ、交流盛んな2つの島で親しまれる美ら花を表現。",category:"ショートカクテル",taste:"ミディアム・ドライ（やや辛口）",ingredients:"泡盛 : 30ml;ヨーグルトリキュール : 10ml;ピーチシロップ : 10ml;フレッシュグレープフルーツジュース : 10ml;グレナデインシロップ : 1/2tsp",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"",award:"総務大臣最優秀賞 ショートカクテル部門",awamoriMl:30,carbonated:false},
  {id:"C00002",name:"キャンディーフラワー",nameEn:"Candy Flower",desc:"強いキャンディーの香りが、まるで沖縄の情熱的な太陽のように、人を惹きつけます。",category:"ロングカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 60ml;ストロベリーリキュール : 30ml;キウイリキュール : 30ml;アップルシロップ : 20ml;レモンジュース : 15ml",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"",award:"総務大臣最優秀賞 ロングカクテル部門",awamoriMl:60,carbonated:false},
  {id:"C00003",name:"The Ocean",nameEn:"The Ocean",desc:"光り輝く海面から飛び出した、優美でたくましいイルカの姿と果てしなく広がる力強く雄大な海を表現。",category:"ショートカクテル",taste:"ミディアム・ドライ（やや辛口）",ingredients:"泡盛 : 30ml;ブルーベリーリキュール : 15ml;ホワイトカカオ : 10ml;ブルーキュラソー : 1tsp;フレッシュライムジュース : 5ml",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"",award:"沖縄県知事賞 ショートカクテル部門",awamoriMl:30,carbonated:false},
  {id:"C00004",name:"マリンルック",nameEn:"Marine Look",desc:"海に親しむ夏のファッション。大きな襟のセーラーカラーは、元気と笑顔あふれる砂辺にお似合いの光景。",category:"ロングカクテル",taste:"ミディアム・ドライ（やや辛口）",ingredients:"泡盛 : 40ml;ヨーグルトリキュール : 10ml;ピニャコラーダシロップ : 10ml;レモンジュース : 1tsp;ジンジャエール : 30ml",distill:"常圧蒸留",glass:"シャンパングラス",recipe:"",award:"沖縄県知事賞 ロングカクテル部門",awamoriMl:40,carbonated:true},
  {id:"C00005",name:"琉華",nameEn:"Ryuka",desc:"日本で一番に咲く沖縄の春の花、寒緋桜。その鮮やかな花をイメージし早く訪れる春の気配を感じて欲しい。",category:"ショートカクテル",taste:"ドライ（辛口）",ingredients:"泡盛 : 30ml;バナナリキュール : 20ml;ピーチシロップ : 10ml;グレナデインシロップ : 1tsp;赤ワイン : 1フロート",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"",award:"総務大臣最優秀賞 ショートカクテル部門",awamoriMl:30,carbonated:false},
  {id:"C00006",name:"オキナワラブソング",nameEn:"Okinawan Love Song",desc:"Okinawaの素晴らしい情景を表したインパクトのある泡盛の良さを生かした味わいが特徴。",category:"ロングカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 35ml;リモンチェッロ : 25ml;ストロベリーリキュール : 7ml;グレープジュース : 30ml;オレンジジュース : 適量",distill:"減圧蒸留",glass:"",recipe:"",award:"総務大臣最優秀賞 ロングカクテル部門",awamoriMl:35,carbonated:false},
  {id:"C00007",name:"ナイトサンディー・ビーチ",nameEn:"Night Sandy Beach",desc:"遠浅の海は、波の音が静かで優しい。夜の砂浜に2人のカップルは、夢を語り合っているのか。沖縄の夜の海を表現。",category:"ショートカクテル",taste:"ミディアム・ドライ（やや辛口）",ingredients:"泡盛 : 30ml;コーヒーリキュール : 10ml;クッキーリキュール : 10ml;生クリーム : 10ml",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"",award:"沖縄県知事賞 ショートカクテル部門",awamoriMl:30,carbonated:false},
  {id:"C00008",name:"笑てぃ",nameEn:"Waratei",desc:"輝く太陽のもと、白い砂浜を裸足で駆け抜けた。深い深い海の中・・潜っていく。胸に刻まれた思い出。",category:"ロングカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 30ml;バナナリキュール : 15ml;グァバジュース : 10ml;Beni : 5ml",distill:"常圧蒸留",glass:"ロックグラス",recipe:"",award:"沖縄県知事賞 ロングカクテル部門",awamoriMl:30,carbonated:false},
  {id:"C00009",name:"スカーレット・トゥインクル",nameEn:"Scarlet Twinkle",desc:"グラスの中で揺らめくクリアな赤色は、海辺のサンセット、そよ風に揺れるハイビスカス。トキメキとキラメキの沖縄の夜を。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;ココナッツリキュール : 15ml;グレナディンリキュール : 15ml;レモンジュース : 1tsp;グレナディンシロップ : 1/2tsp",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてカクテルグラスに注ぐ。チェリーを飾る",award:"入賞",awamoriMl:30,carbonated:false},
  {id:"C00010",name:"アスール・プラージャ",nameEn:"Asul Playa",desc:"アスールとはスペイン語で\"青い\"という意味。プラージャは\"渚\"。沖縄の素晴らしい青い海と澄んだ青い空のイメージ。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;パイナップルジュース : 15ml;カルピス : 15ml;ブルーキュラソー : 10ml;レモンジュース : 10ml",distill:"減圧蒸留",glass:"",recipe:"シェーカーに氷とトニックウォーター以外の材料を入れシェーク。クラッシュドアイスを詰めたグラスに注ぐ",award:"入賞",awamoriMl:30,carbonated:false},
  {id:"C00011",name:"琉球シンドローム",nameEn:"Ryukyu Syndrome",desc:"沖縄にやって来てそのまま居着いてしまう\"沖縄病\"。辛口の食前酒的な正統派カクテル。",category:"ショートカクテル",taste:"ドライ（辛口）",ingredients:"泡盛 : 30ml;ドライベルモット : 20ml;ホワイトミント : 10ml;アンゴスチュラビターズ : 1dash",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"ミキシンググラスに氷と材料を入れてステアし、グラスに注ぐ",award:"入賞",awamoriMl:30,carbonated:false},
  {id:"C00013",name:"うりずん",nameEn:"Urizun",desc:"うりずんとは沖縄の旧暦2、3月頃を指す語。メロンの甘みとヒラミレモンの酸味がほどよくきいたカクテル。",category:"ショートカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 40ml;メロンリキュール : 10ml;ヒラミレモン : 10ml",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてカクテルグラスに注ぐ。パイナップルを飾る",award:"入賞",awamoriMl:40,carbonated:false},
  {id:"C00014",name:"みやらび",nameEn:"Miyarabi",desc:"「美童」と書き若い娘や純粋な心をもった子ども。すももジュースを使った一風変わったトロピカルカクテル。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;ヒラミレモン : 20ml;ホワイトキュラソー : 10ml;すももジュース : 適量",distill:"減圧蒸留",glass:"",recipe:"シェーカーに材料と氷を入れシェーク。氷を詰めたグラスに注ぎ、すももジュースを注ぐ",award:"入賞",awamoriMl:30,carbonated:false},
  {id:"C00015",name:"レキオ",nameEn:"Lequio",desc:"16世紀頃ヨーロッパ人が琉球を尊敬を込めて呼んだ呼称。ライチに酸味を加えた女性にも飲みやすいカクテル。",category:"ショートカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 30ml;ライチリキュール : 20ml;ヒラミレモン : 10ml;パルフェタムール : 1tsp",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてカクテルグラスに注ぐ。チェリーを飾る",award:"入賞",awamoriMl:30,carbonated:false},
  {id:"C00016",name:"琉美",nameEn:"Ryubi",desc:"琉球舞踊の艶やかさや伝統的な建造物の美しさ。グァバジュースをふんだんに使ったロングドリンクス。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 40ml;クレーム・ド・カシス : 10ml;ヒラミレモン : 10ml;グァバジュース : 適量",distill:"減圧蒸留",glass:"ロックグラス",recipe:"シェーカーに氷と材料を入れシェーク。氷を詰めたタンブラーに注ぎグァバジュースを注ぐ",award:"入賞",awamoriMl:40,carbonated:false},
  {id:"C00017",name:"さくら",nameEn:"Sakura",desc:"日本一早いさくら祭り。本部町の八重岳桜花見まつりをイメージした、淡いピンク系のカクテル。",category:"ショートカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 40ml;アプリコットブランデー : 10ml;ヒラミレモン : 10ml;クレーム・ド・カシス : 1/2tsp",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてカクテルグラスに注ぐ。チェリーとミントを飾る",award:"入賞",awamoriMl:40,carbonated:false},
  {id:"C00018",name:"ニライカナイ",nameEn:"Nirai Kanai",desc:"海の彼方にあるとされる理想郷。ブルーキュラソーとパイナップルのトロピカルカクテル。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;ブルーキュラソー : 20ml;ヒラミレモン : 10ml;ガムシロップ : 10ml;フレッシュパイナップル : 適量",distill:"常圧蒸留",glass:"",recipe:"材料とクラッシュドアイスをミキサーにかけ、グラスに注ぐ。パイナップルを飾る",award:"入賞",awamoriMl:30,carbonated:false},
  {id:"C00019",name:"アワモリ・トニック",nameEn:"Awamori Tonic",desc:"スタンダードカクテルの定番。清涼感のあるスッキリ、さっぱりとした味わい。",category:"ロングカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 45ml;トニックウォーター : 適量;ライム : 1/6カット",distill:"減圧蒸留",glass:"タンブラー",recipe:"グラスに氷を入れ、ライムを絞り入れる。泡盛を注ぎ、トニックウォーターで満たす。軽くステア",award:"",awamoriMl:45,carbonated:true},
  {id:"C00020",name:"泡盛マルガリータ",nameEn:"Awamori Margarita",desc:"塩の味とライムの酸味で、すっきりとした口当たり。スペイン語でマーガレットの意。",category:"ショートカクテル",taste:"ミディアム",ingredients:"泡盛 : 30ml;ホワイトキュラソー : 20ml;ライムジュース : 10ml",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"グラスを塩でスノースタイルに。シェーカーに氷と材料を入れシェーク",award:"",awamoriMl:30,carbonated:false},
  {id:"C00021",name:"フローズン泡盛ダイキリ",nameEn:"Frozen Awamori Daiquiri",desc:"キューバの鉱山で暑さしのぎに生まれたダイキリ。ヘミングウェイがこよなく愛したフローズンスタイル。",category:"ロングカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 45ml;ホワイトキュラソー : 1tsp;ライムジュース : 15ml;シロップ : 1tsp",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"材料とクラッシュドアイスをミキサーにかけ、グラスに注ぐ。ストローを添える",award:"",awamoriMl:45,carbonated:false},
  {id:"C00022",name:"泡盛サンライズ",nameEn:"Awamori Sunrise",desc:"グラスの中に美しい朝焼けを演出した、情熱的カクテルの定番。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;オレンジジュース : 60ml;グレナディンシロップ : 1tsp",distill:"常圧蒸留",glass:"タンブラー",recipe:"グラスに氷を入れ泡盛とジュースを注ぎステア。グレナディンシロップを静かに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00023",name:"しまボール",nameEn:"Shima Ball",desc:"アメリカで生まれたコーラと沖縄生まれの泡盛の組み合わせ。うちなー万歳！",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;コーク : 適量;ライム : 1/6カット",distill:"減圧蒸留",glass:"タンブラー",recipe:"グラスに氷を入れ、ライムを絞り入れる。泡盛を注ぎコークで満たす。軽くステア",award:"",awamoriMl:30,carbonated:true},
  {id:"C00024",name:"響",nameEn:"Toyomi",desc:"シェリーの香り漂うグラスを傾けて。カシスの甘美さとカンパリのほろ苦さが上品に。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;クレームドカシス : 15ml;ドライシェリー : 10ml;カンパリ : 5ml",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00025",name:"美南海",nameEn:"Minami",desc:"美しい南の海で戯れる熱帯魚たち。すみれ色のパルフェタムールで南の海を表現。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;パルフェタムール : 15ml;レモンリキュール : 10ml;レモンジュース : 5ml",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてグラスに注ぐ。レモンピールを飾る",award:"",awamoriMl:30,carbonated:false},
  {id:"C00029",name:"黄金の花",nameEn:"Kogane No Hana",desc:"その花を見た人は幸せになるという黄金の花。マンゴーリキュールで鮮やかな黄金色に。",category:"ショートカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 30ml;マンゴリキュール : 15ml;レモンジュース : 15ml;オレンジジュース : 1tsp",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00030",name:"A-sinカクテル",nameEn:"A-sin Cocktail",desc:"Aサインバーから泡盛とカクテル文化がスタート。ハッカ風味とトニックの清涼感。",category:"ロングカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 30ml;バーボン : 15ml;グリーンペパーミント : 10ml;レモンジュース : 1tsp;トニックウォーター : 適量",distill:"減圧蒸留",glass:"シャンパングラス",recipe:"グラスにトニックウォーターを注ぎ、シェークした材料をフロート",award:"",awamoriMl:30,carbonated:true},
  {id:"C00031",name:"ハイビスカス",nameEn:"Hibiscus",desc:"沖縄の県花ハイビスカス。すももの風味と甘酸っぱさが口の中に広がるスウィートカクテル。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;すももジュース : 20ml;アップルリキュール : 10ml",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00033",name:"サンド・スター",nameEn:"Sand Star",desc:"南の島の星砂をイメージ。パッションフルーツのリキュールにミントのアクセント。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;ブルーキュラソー : 15ml;パッションリキュール : 10ml;ホワイトミント : 10ml;コーディアルライム : 適量",distill:"常圧蒸留",glass:"ロックグラス",recipe:"シェーカーに氷と材料を入れシェーク。クラッシュドアイスを詰めたグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00035",name:"パイナップルドール",nameEn:"Pineapple Doll",desc:"沖縄の特産品パイナップルをふんだんに使ったトロピカルドリンク。黒糖シロップがアクセント。",category:"ロングカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 40ml;ホワイトキュラソー : 20ml;パイナップルジュース : 10ml;レモンジュース : 10ml;黒糖シロップ : 15ml",distill:"常圧蒸留",glass:"",recipe:"シェーカーに氷と材料を入れシェークしてグラスに注ぐ。パイナップルを飾る",award:"",awamoriMl:40,carbonated:false},
  {id:"C00036",name:"リーフ・ライン",nameEn:"Leaf Line",desc:"うりずんの頃の爽やかな海辺。パイナップルの甘味にペパーミントの爽快さをプラス。",category:"ショートカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 30ml;パイナップルジュース : 20ml;グリーンペパーミント : 10ml;レモンジュース : 1tsp",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れシェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00037",name:"ティーダ",nameEn:"Teeda",desc:"沖縄の照りつける太陽をイメージ。方言で「太陽」の意。グァバジュースで仕上げたトロピカルカクテル。",category:"ショートカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 40ml;グリーンバナナ : 10ml;グァバジュース : 10ml;レモンジュース : 10ml",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れシェークしてグラスに注ぐ。バナナを飾る",award:"",awamoriMl:40,carbonated:false},
  {id:"C00039",name:"守礼",nameEn:"Syu-Rei",desc:"礼節を重んじる琉球の心。白桃ネクターの穏やかで上品な甘み。琉球王朝のもてなしの心。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;アップルリキュール : 20ml;白桃ネクター : 10ml;レモンジュース : 1tsp",distill:"減圧蒸留",glass:"リキュールグラス",recipe:"シェーカーに氷と材料を入れシェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00040",name:"サザンコール",nameEn:"Southern Call",desc:"海と空、そして素敵な夜が呼んでいます。南の島からの清涼感あふれる作品。",category:"ロングカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 30ml;バナナリキュール : 20ml;パイナップルジュース : 10ml;ブルーキュラソー : 1tsp;トニックウォーター : 適量",distill:"常圧蒸留",glass:"シャンパングラス",recipe:"シェーカーに氷と材料を入れシェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:true},
  {id:"C00041",name:"万音",nameEn:"Ma-Non",desc:"耳を澄ませば聞こえてくる自然の音色、万音。女性にお勧めしたい甘美なカクテル。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;バナナリキュール : 20ml;ホワイトカカオ : 10ml;レモンジュース : 1tsp",distill:"常圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れシェークしてグラスに注ぐ。チェリーを飾る",award:"",awamoriMl:30,carbonated:false},
  {id:"C00042",name:"アイランダー",nameEn:"Islander",desc:"しまんちゅのもてなしカクテル。ライチとグレープフルーツの涼し気なカクテル。",category:"ロングカクテル",taste:"ミディアム・スウィート（やや甘口）",ingredients:"泡盛 : 30ml;ライチリキュール : 15ml;グレープフルーツジュース : 15ml;ブルーキュラソー : 1tsp;トニックウォーター : 適量",distill:"減圧蒸留",glass:"",recipe:"グラスにトニックウォーターを注ぎ、残りの材料をシェークしてフロート",award:"",awamoriMl:30,carbonated:true},
  {id:"C00044",name:"ゴーヤーカクテル",nameEn:"Goya Cocktail",desc:"沖縄の代表的な夏野菜ゴーヤー。食欲を刺激する微かな苦みのアペリティフ。",category:"ロングカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 45ml;ホワイトキュラソー : 20ml;レモンジュース : 20ml;シロップ : 10ml;ニガウリスライス : 2枚",distill:"減圧蒸留",glass:"",recipe:"材料とクラッシュドアイスをミキサーにかけ、グラスに注ぐ。ニガウリを飾る",award:"",awamoriMl:45,carbonated:false},
  {id:"C00045",name:"花織",nameEn:"Hana-Ui",desc:"独特の模様織物「花織」。ピーチとライチリキュールを使った女性好みの甘口カクテル。",category:"ショートカクテル",taste:"スウィート（甘口）",ingredients:"泡盛 : 30ml;ピーチリキュール : 20ml;ライチリキュール : 20ml;ライムジュース : 10ml;レッドキュラソー : 1tsp",distill:"減圧蒸留",glass:"カクテルグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてグラスに注ぐ",award:"",awamoriMl:30,carbonated:false},
  {id:"C00046",name:"琉波",nameEn:"Ryu-Ha",desc:"岸壁に打ちつける波が散るイメージ。チャールストンとグレープフルーツの相性が抜群。",category:"ショートカクテル",taste:"ミディアム（中口）",ingredients:"泡盛 : 30ml;パッションリキュール : 10ml;グレープフルーツジュース : 20ml;レモンジュース : 10ml;ペパーミント : 1tsp",distill:"減圧蒸留",glass:"サワーグラス",recipe:"シェーカーに氷と材料を入れ、シェークしてサワーグラスに注ぐ。チェリーを飾る",award:"",awamoriMl:30,carbonated:false},
];

// === FOOD DATA ===
const FOOD_DATA = [
  {name:"ナッツ",intensity:2,type:"塩味・香ばしい",salt:2,sweet:1,sour:1,oil:3,recDistill:"常圧蒸留"},
  {name:"チーズ盛り合わせ",intensity:4,type:"濃厚・塩味",salt:3,sweet:1,sour:1,oil:4,recDistill:"常圧蒸留"},
  {name:"生ハム",intensity:3,type:"塩味・旨味",salt:4,sweet:1,sour:1,oil:2,recDistill:"常圧蒸留"},
  {name:"オリーブ",intensity:2,type:"塩味・酸味",salt:3,sweet:1,sour:2,oil:3,recDistill:"どちらでも"},
  {name:"枝豆",intensity:1,type:"あっさり",salt:2,sweet:1,sour:1,oil:1,recDistill:"どちらでも"},
  {name:"フライドポテト",intensity:3,type:"塩味・油",salt:3,sweet:1,sour:1,oil:5,recDistill:"減圧蒸留"},
  {name:"唐揚げ",intensity:4,type:"濃厚・油",salt:3,sweet:1,sour:1,oil:5,recDistill:"減圧蒸留"},
  {name:"ピザ",intensity:4,type:"濃厚・塩味",salt:3,sweet:2,sour:2,oil:4,recDistill:"どちらでも"},
  {name:"カルパッチョ",intensity:2,type:"あっさり・酸味",salt:2,sweet:1,sour:3,oil:2,recDistill:"減圧蒸留"},
  {name:"アヒージョ",intensity:4,type:"濃厚・にんにく",salt:3,sweet:1,sour:1,oil:5,recDistill:"常圧蒸留"},
  {name:"タコス",intensity:4,type:"スパイシー",salt:3,sweet:1,sour:2,oil:3,recDistill:"常圧蒸留"},
  {name:"ソーセージ盛り合わせ",intensity:4,type:"塩味・旨味",salt:4,sweet:1,sour:1,oil:4,recDistill:"常圧蒸留"},
  {name:"カプレーゼ",intensity:2,type:"あっさり・酸味",salt:2,sweet:1,sour:2,oil:2,recDistill:"減圧蒸留"},
  {name:"ブルスケッタ",intensity:3,type:"酸味・香ばしい",salt:2,sweet:1,sour:3,oil:2,recDistill:"どちらでも"},
  {name:"スモークサーモン",intensity:3,type:"塩味・燻製",salt:3,sweet:1,sour:1,oil:3,recDistill:"常圧蒸留"},
  {name:"チョコレート",intensity:4,type:"甘味・苦味",salt:1,sweet:5,sour:1,oil:3,recDistill:"常圧蒸留"},
  {name:"ドライフルーツ",intensity:3,type:"甘味・酸味",salt:1,sweet:4,sour:3,oil:1,recDistill:"減圧蒸留"},
  {name:"クラッカー&ディップ",intensity:2,type:"塩味・軽い",salt:2,sweet:1,sour:1,oil:2,recDistill:"どちらでも"},
  {name:"ポテトチップス",intensity:3,type:"塩味・油",salt:4,sweet:1,sour:1,oil:4,recDistill:"減圧蒸留"},
  {name:"焼き鳥",intensity:4,type:"塩味・旨味",salt:3,sweet:2,sour:1,oil:3,recDistill:"常圧蒸留"},
];

// === AWAMORI BRANDS ===
const AWAMORI_BRANDS = [
  {brand:"残波ホワイト 25度",maker:"比嘉酒造",distill:"減圧蒸留",degree:25,note:"フルーティーな香りとすっきりした飲み口",url:"https://zanpa.okinawa/",kodawari:"1948年読谷村創業。「女性や泡盛を知らない方でも楽しめる泡盛」を目指して開発。沖縄県内外で広く親しまれる代表銘柄。"},
  {brand:"残波ブラック 30度",maker:"比嘉酒造",distill:"減圧蒸留",degree:30,note:"黒麹のキリッとしたのど越し",url:"https://zanpa.okinawa/",kodawari:"1948年読谷村創業。「女性や泡盛を知らない方でも楽しめる泡盛」を目指して開発。沖縄県内外で広く親しまれる代表銘柄。"},
  {brand:"夢航海 30度",maker:"忠孝酒造",distill:"減圧蒸留",degree:30,note:"青リンゴのような爽やかな香り",url:"https://www.chuko-awamori.com/",kodawari:"蔵元でありながら窯元でもある世界唯一の酒蔵。泡盛熟成用の南蛮荒焼甕を自社窯で製作し、伝統製法を再現。"},
  {brand:"島唄 25度",maker:"まさひろ酒造",distill:"減圧蒸留",degree:25,note:"清酒酵母使用のフルーティー泡盛",url:"https://www.masahiro.co.jp/",kodawari:"1883年創業、140年超の歴史。清酒酵母を使用した減圧蒸留泡盛に古酒をブレンドした新しいスタイル。"},
  {brand:"ender 25度",maker:"瑞穂酒造",distill:"減圧蒸留",degree:25,note:"日本酒のような吟醸香",url:"https://mizuhoshuzo.co.jp/",kodawari:"業界初の「天然吟香酵母」使用。商品名は沖縄方言で「やさしい人」を意味し、華やかな香りが特徴。"},
  {brand:"請福マリンボトル",maker:"請福酒造",distill:"減圧蒸留",degree:30,note:"泡盛初の減圧蒸留商品",url:"https://www.seifuku.co.jp/",kodawari:"1949年石垣島創業。昔ながらの直火釜蒸留にこだわり、八重山の風土を活かした泡盛造り。"},
  {brand:"かりゆし 30度",maker:"新里酒造",distill:"減圧蒸留",degree:30,note:"沖縄最古の蔵元の減圧蒸留",url:"https://shinzato-shuzo.co.jp/",kodawari:"沖縄最古の蔵元として175年の歴史。「かりゆし」は沖縄の言葉で「めでたい」を意味する。"},
  {brand:"菊之露 akari",maker:"菊之露酒造",distill:"減圧蒸留",degree:25,note:"クリアで透明感のある味わい",url:"https://www.kikunotsuyu.co.jp/",kodawari:"宮古島の硬水（カルシウム・ミネラル豊富）を仕込み水に使用。「最高に楽しい瞬間をつくる」が使命。"},
  {brand:"瑞泉 30度",maker:"瑞泉酒造",distill:"常圧蒸留",degree:30,note:"首里の老舗。1887年創業",url:"https://www.zuisen.co.jp/",kodawari:"1887年首里城下町で創業。戦禍を奇跡的に生き延びた戦前の黒麹菌を使い復活させた「御酒」は泡盛の源流。"},
  {brand:"松藤 30度",maker:"崎山酒造廠",distill:"常圧蒸留",degree:30,note:"常圧蒸留のみ。旨味へのこだわり",url:"https://sakiyamashuzo.jp/",kodawari:"1905年創業。手間のかかる「三日麹」製法にこだわり、恩納岳の湧き水で仕込む。深いコクが特徴。"},
  {brand:"久米島の久米仙 30度",maker:"久米島の久米仙",distill:"常圧蒸留",degree:30,note:"全麹仕込み・常圧蒸留",url:"https://www.k-kumesen.co.jp/",kodawari:"久米島の名水を使用。厳選した南方硬質米を用い、麹・もろみ造りは人の手で自然に近い状態で行う。"},
  {brand:"菊之露 30度",maker:"菊之露酒造",distill:"常圧蒸留",degree:30,note:"宮古島の硬水使用",url:"https://www.kikunotsuyu.co.jp/",kodawari:"宮古島の硬水と黒麹菌の相性を活かした味わいが特徴。宮古島の代表的酒造所。"},
  {brand:"直火請福 30度",maker:"請福酒造",distill:"常圧蒸留",degree:30,note:"独自直火蒸留釜。香ばしい風味",url:"https://www.seifuku.co.jp/",kodawari:"1949年石垣島創業。昔ながらの直火釜蒸留にこだわり、八重山の風土を活かした泡盛造り。"},
  {brand:"八重泉 30度",maker:"八重泉酒造",distill:"常圧蒸留",degree:30,note:"石垣島。直火蒸留にこだわる",url:"https://yaesen.com/",kodawari:"1955年石垣島創業。伝統的な直火蒸留製法を守りつつ、長期樽貯蔵にも取り組む革新的な蔵元。"},
  {brand:"暖流 30度",maker:"神村酒造",distill:"常圧蒸留",degree:30,note:"ウイスキー樽熟成泡盛",url:"https://kamimura-shuzo.co.jp/",kodawari:"明治15年創業。日本初のウィスキー樽貯蔵泡盛「暖流」を10年の研究開発を経て実現。琥珀色の泡盛。"},
  {brand:"春雨 30度",maker:"宮里酒造所",distill:"常圧蒸留",degree:30,note:"少量生産の希少銘柄",url:"",kodawari:"1946年那覇市首里で創業。赤瓦屋根の小さな蔵で職人3名が手造りする希少な泡盛。伝説的な蔵元。"},
  {brand:"くら 3年古酒",maker:"ヘリオス酒造",distill:"常圧蒸留",degree:25,note:"銅製蒸留器・オーク樽熟成",url:"https://www.helios-syuzo.co.jp/",kodawari:"1961年創業。「古酒くら」は34年以上のロングセラー。オーク樽で3年以上熟成させた琥珀色の古酒100%泡盛。"},
  {brand:"白百合 30度",maker:"池原酒造",distill:"常圧蒸留",degree:30,note:"個性的な風味で人気",url:"https://www.shirayuri-ikehara.com/",kodawari:"1951年石垣島創業。古民家蔵で全工程手作業・天然醸造・直火釜蒸留。世界的レストラン「noma」にも採用。"},
  {brand:"泡波 30度",maker:"波照間酒造所",distill:"常圧蒸留",degree:30,note:"幻の泡盛。極少生産",url:"http://awanami.net/",kodawari:"日本最南端・波照間島の小さな酒造所。製造量が極めて少なく「幻の泡盛」と呼ばれる入手困難な希少銘柄。"},
  {brand:"残波プレミアム 5年古酒",maker:"比嘉酒造",distill:"常圧蒸留",degree:35,note:"100%甕貯蔵5年古酒",url:"https://zanpa.okinawa/",kodawari:"1948年読谷村創業。「女性や泡盛を知らない方でも楽しめる泡盛」を目指して開発。沖縄県内外で広く親しまれる代表銘柄。"},
];

// === COCKTAIL IMAGES (Unsplash free) ===
const COCKTAIL_IMAGES = {
  short: [
    "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=300&fit=crop&auto=format",
    "https://images.unsplash.com/photo-1544320324-b3235e43b5cc?w=400&h=300&fit=crop&auto=format",
    "https://images.unsplash.com/photo-1661002529725-5e55e8a58923?w=400&h=300&fit=crop&auto=format",
  ],
  long: [
    "https://images.unsplash.com/photo-1587223962217-f4e4f399eca4?w=400&h=300&fit=crop&auto=format",
    "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400&h=300&fit=crop&auto=format",
    "https://images.unsplash.com/photo-1745076437587-82cbb1e78ac3?w=400&h=300&fit=crop&auto=format",
  ],
};
